from typing import Any, Callable, Dict, List, Tuple
import flet as ft


class TextField(ft.TextField):
    def __init__(
        self,
        value: str | None = None,
        keyboard_type: ft.KeyboardType | None = None,
        multiline: bool | None = None,
        min_lines: int | None = None,
        max_lines: int | None = None,
        max_length: int | None = None,
        password: bool | None = None,
        can_reveal_password: bool | None = None,
        read_only: bool | None = None,
        shift_enter: bool | None = None,
        text_align: ft.TextAlign | None = None,
        autofocus: bool | None = None,
        capitalization: ft.TextCapitalization | None = None,
        autocorrect: bool | None = None,
        enable_suggestions: bool | None = None,
        smart_dashes_type: bool | None = None,
        smart_quotes_type: bool | None = None,
        show_cursor: bool | None = None,
        cursor_color: str | None = None,
        cursor_width: int | float | None = None,
        cursor_height: int | float | None = None,
        cursor_radius: int | float | None = None,
        selection_color: str | None = None,
        input_filter: ft.InputFilter | None = None,
        autofill_hints: None | ft.AutofillHint | List[ft.AutofillHint] = None,
        on_change: Callable[[ft.ControlEvent], None] | None = None,
        on_submit: Callable[[ft.ControlEvent], None] | None = None,
        on_focus: Callable[[ft.ControlEvent], None] | None = None,
        on_blur: Callable[[ft.ControlEvent], None] | None = None,
        text_size: int | float | None = None,
        text_style: ft.TextStyle | None = None,
        text_vertical_align: ft.VerticalAlignment | int | float | None = None,
        label: str | None = None,
        label_style: ft.TextStyle | None = None,
        icon: str | None = None,
        border: ft.InputBorder | None = None,
        color: str | None = None,
        bgcolor: str | None = None,
        border_radius: int | float | ft.BorderRadius | None = None,
        border_width: int | float | None = None,
        border_color: str | None = None,
        focused_color: str | None = None,
        focused_bgcolor: str | None = None,
        focused_border_width: int | float | None = None,
        focused_border_color: str | None = None,
        content_padding: int | float | ft.Padding | None = None,
        dense: bool | None = None,
        filled: bool | None = None,
        fill_color: str | None = None,
        hover_color: str | None = None,
        hint_text: str | None = None,
        hint_style: ft.TextStyle | None = None,
        helper_text: str | None = None,
        helper_style: ft.TextStyle | None = None,
        counter_text: str | None = None,
        counter_style: ft.TextStyle | None = None,
        error_text: str | None = None,
        error_style: ft.TextStyle | None = None,
        prefix: ft.Control | None = None,
        prefix_icon: str | None = None,
        prefix_text: str | None = None,
        prefix_style: ft.TextStyle | None = None,
        suffix: ft.Control | None = None,
        suffix_icon: str | None = None,
        suffix_text: str | None = None,
        suffix_style: ft.TextStyle | None = None,
        ref: ft.Ref | None = None,
        key: str | None = None,
        width: int | float | None = None,
        height: int | float | None = None,
        expand: None | bool | int = None,
        expand_loose: bool | None = None,
        col: Dict[str, int | float] | int | float | None = None,
        opacity: int | float | None = None,
        rotate: int | float | ft.Rotate | None = None,
        scale: int | float | ft.Scale | None = None,
        offset: ft.Offset | Tuple[float | int, float | int] | None = None,
        aspect_ratio: int | float | None = None,
        animate_opacity: bool | int | ft.Animation | None = None,
        animate_size: bool | int | ft.Animation | None = None,
        animate_position: bool | int | ft.Animation | None = None,
        animate_rotation: bool | int | ft.Animation | None = None,
        animate_scale: bool | int | ft.Animation | None = None,
        animate_offset: bool | int | ft.Animation | None = None,
        on_animation_end: Callable[[ft.ControlEvent], None] | None = None,
        tooltip: str | None = None,
        visible: bool | None = None,
        disabled: bool | None = None,
        data: Any = None,
        rtl: bool | None = None,
        adaptive: bool | None = None,
    ):
        super().__init__(
            value,
            keyboard_type,
            multiline,
            min_lines,
            max_lines,
            max_length,
            password,
            can_reveal_password,
            read_only,
            shift_enter,
            text_align,
            autofocus,
            capitalization,
            autocorrect,
            enable_suggestions,
            smart_dashes_type,
            smart_quotes_type,
            show_cursor,
            cursor_color,
            cursor_width,
            cursor_height,
            cursor_radius,
            selection_color,
            input_filter,
            autofill_hints,
            on_change,
            on_submit,
            on_focus,
            on_blur,
            text_size,
            text_style,
            text_vertical_align,
            label,
            label_style,
            icon,
            border,
            color,
            bgcolor,
            border_radius,
            border_width,
            border_color,
            focused_color,
            focused_bgcolor,
            focused_border_width,
            focused_border_color,
            content_padding,
            dense,
            filled,
            fill_color,
            hover_color,
            hint_text,
            hint_style,
            helper_text,
            helper_style,
            counter_text,
            counter_style,
            error_text,
            error_style,
            prefix,
            prefix_icon,
            prefix_text,
            prefix_style,
            suffix,
            suffix_icon,
            suffix_text,
            suffix_style,
            ref,
            key,
            width,
            height,
            expand,
            expand_loose,
            col,
            opacity,
            rotate,
            scale,
            offset,
            aspect_ratio,
            animate_opacity,
            animate_size,
            animate_position,
            animate_rotation,
            animate_scale,
            animate_offset,
            on_animation_end,
            tooltip,
            visible,
            disabled,
            data,
            rtl,
            adaptive,
        )

        self.adaptive = True
        # self.border_color = "#063620"
        self.border_width = 1.75
        self.border_radius = 9.42  # 3 PI

        # self.focused_border_color = ft.colors.BLUE_900
        self.focused_border_width = 2.9
